### ISSUE TITLE
Android popup disapears

### ISSUE THREAD

**Issue by mustberain** [scazzy/Popelt#6]
Hi, first of all; nice work its perfect @ iOS!

Android 5.0.1 (chrome browser, nexus 5) gives me trouble though. Seems like it only works when the button which triggers the popup is at the same position as the popup itself. For example, if the button is in the header and the popup is in the center, the popup disappears instantly. If the button is in the middle, and so is the popup; it works like a charm.

If more information needed, let me know. Thank you

**Comment by scazzy** [comment]
Hi mustberain
Thanks for using Popelt.

Can you share some screenshot or usage demo that I can test?

**Comment by mustberain** [comment]
Hi scazzy,

I'm sorry I found the cause and it has nothing to do with your code. Its happening when i trigger the popup with : 
$(document).on("tap", ".classname", function()  
instead of
$(document).on("click", ".classname", function() 

Its working fine now, maybe useful for someone else reading this.

**Comment by scazzy** [comment]
@mustberain thanks for updating. You can start this repo if you would want to get update on next release of Popelt.

You may close this issue.
Thanks for using Popelt
